### ISSUE TITLE
setelah direkon muncul no fakturnya u10t16010001906

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#109]

**Comment by wildanm** [comment]
Ini maksudnya apa ?

**Comment by albeth** [comment]
jd itu fakturnya kmrn mau dilunasin kaga muncul setelah direkon muncul

**Comment by wildanm** [comment]
berarti faktur itu belum dilunasi (atau pelunasannya tidak balance). 

Nomor faktur itu sudah dilunasi belum ? di receipt per nomor fakturnya ada ?

**Comment by albeth** [comment]
iya kmrn mau dilunasin kaga ketemu (kaga ada dilist pelunasan tunai tgl 9-01-2016).....tapi skrg dah dilunasin.....cuma itu faktur bisa muncul setelah rekon.....apa gara2 rekon u blom auto jdnya kaya gt

**Comment by wildanm** [comment]
Sudah dibuka issue baru untuk ini #110
