### ISSUE TITLE
penghapusan data fungsi notifikasi di http://erp2012.tirta/transactions/sales yg nilai nol botol kosong dan isinya masih muncul

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#125]

**Comment by wildanm** [comment]
Ini bukannya udah ya ?
Pada tanggal 4 Jun 2016 10:04 AM, "albeth" <notifications@github.com>
menulis:

**Comment by albeth** [comment]
ohhh ini lebih dari sebulan yah... sebab bulan 5 masih ada muncul dikira kok masih ada yg nol

**Comment by wildanm** [comment]
Yg tombol kiri itu semuanya. Kalau yg satu lagi, yg ada tanda silangnya itu
yg usianya lebih dari sebulan
Pada tanggal 4 Jun 2016 10:10 AM, "albeth" <notifications@github.com>
menulis:
