### ISSUE TITLE
notifikasi yg ke 3 dihttp://erp2012.tirta/transactions/sales  jgn dimuncul kan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#126]

**Comment by wildanm** [comment]
Jumlah kirim nol dan botol kosong nol dalam faktur digunakan untuk laporan
berapa kali n kirim ke pelanggan tapi tidak ada pengambilan
Pada tanggal 4 Jun 2016 10:24 AM, "albeth" <notifications@github.com>
menulis:

**Comment by wildanm** [comment]
Done i02bc5b7 (bitbucket)
