### ISSUE TITLE
http://tirtaerp.lodan/reports/insentif#

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#130]
hasil jumlah rincian insentif tidak sama dengan popup diklik nama atau insentif satu kenek

**Comment by wildanm** [comment]
Tampilkan screenshoot pilihan2 di form insentif, dan yg beda. Saya klik tidak ada masalah soalnya.

**Comment by albeth** [comment]
jd jumlah total masing2 kolom insentif di laporan luar tidak sama dengan pop up

**Comment by albeth** [comment]
![screenshot from 2016-06-10 11 55 27](https://cloud.githubusercontent.com/assets/17263267/15954537/3f25b05e-2f02-11e6-8068-23d95e0ad398.png)
![screenshot from 2016-06-10 11 55 56](https://cloud.githubusercontent.com/assets/17263267/15954539/44dc8b94-2f02-11e6-8c21-9762fe99c772.png)

**Comment by wildanm** [comment]
Done in 036c158 (bitbucket)
