### ISSUE TITLE
Tambahkan Behavior Timestampable dan Signable TblSalehHPabrik dan TblSalesDPabrik

### ISSUE THREAD

**Issue by wildanm** [OpenThink-Labs/TirtaERP#134]
Untuk menambahkan kolom created_at, updated_at, updated_by dan created_by di tabel tbl_sales_h_pabrik dan tbl_sales_d_pabrik

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

`ALTER TABLE `tbl_sales_h` ADD `created_at` DATETIME NULL AFTER `piutang`, ADD `updated_at` DATETIME NULL AFTER `created_at`, ADD `created_by` BIGINT(20) NOT NULL AFTER `updated_at`, ADD `updated_by` BIGINT(20) NOT NULL AFTER `created_by`;`

> ALTER TABLE `tbl_sales_d` ADD `created_at` DATETIME NULL AFTER `ndisc`, ADD `updated_at` DATETIME NULL AFTER `created_at`, ADD `created_by` BIGINT(20) NOT NULL AFTER `updated_at`, ADD `updated_by` BIGINT(20) NOT NULL AFTER `created_by`;

**Comment by wildanm** [comment]
Done in in (bitbucket a99abc7), setelah jalan harus jalankan sql diatas.

**Comment by albeth** [comment]
ini update sqlnya di phpmyadmin bisa?

**Comment by wildanm** [comment]
Bisa
Pada tanggal 10 Jun 2016 5:02 PM, "albeth" <notifications@github.com>
menulis:
