### ISSUE TITLE
http://tirtaerp.sekolah/reports/daily/sales/per/invoice/payment/type

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#152]
1.dibuatkan versi cetak pdf
2. klik lihat laporan keterangan diatas perjenis bayar blom sesuai dengan rinciannya masih nol penjualannya walaupun ada penjualannya

**Comment by wildanm** [comment]
Yang nomor 2 maksudnya apa ya ?

**Comment by albeth** [comment]
Total masing2 perjenis bayarnya masih nol......walaupun ada penjualannya

**Comment by wildanm** [comment]
Yg muncul memang yg dipilih aja jenis bayarnya. Yg resume diatas tabel nya
kan ?

Pada tanggal 29 Jun 2016 6:44 AM, "albeth" <notifications@github.com>
menulis:

**Comment by wildanm** [comment]
Done in bc58cac (bitbucket)
