### ISSUE TITLE
disetiap menu laporan penjualan mobil dan supir non aktif ditampilkan sesuai dengan pilihan tgl ketika input faktur penjualan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#156]

**Comment by wildanm** [comment]
Tolong url setiap laporam yg mau diubah di tulis.

Pada tanggal 2 Jul 2016 10:31 AM, "albeth" <notifications@github.com>
menulis:

**Comment by albeth** [comment]
http://erp2012.tirta/reports/harian/mobil
http://erp2012.tirta/reports/daily/sales/per/vehicle/berdasarkan/faktur

**Comment by wildanm** [comment]
Done in aa5901f (bitbucket)
