### ISSUE TITLE
status stok dan jenis pergerakannya blom ada listnya

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#159]
1. http://tirtaerp.sekolah/inventory/inventory/adjustments?NewAdjustment=1
2. http://tirtaerp.sekolah/inventory/status/transfer?NewTransfer=1

**Comment by wildanm** [comment]
Ini harus di team

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

```
INSERT IGNORE INTO movement_types (id, name, inactive) VALUES
(1, 'Penyesuaian Galon / Karton Isi', 0),
(2, 'Penyesuaian Galon Kosong', 0),
(3, 'Penyesuaian Galon Bocor', 0),
(4, 'Penyesuaian Galon Pecah Kosong', 0),
(5, 'Penyesuaian Galon Pecah Isi', 0),
(6, 'Penyesuain Galon Air Kotor', 0),
(7, 'Penyesuaian Galon Merek Lain', 0);
```

**Comment by wildanm** [comment]
Jalankan SQL Berikut : 

`ALTER TABLE stock_moves CHANGE person_id person_id INT(11) NULL;`

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

`ALTER TABLE stock_moves CHANGE is_closed is_closed TINYINT(1) NOT NULL DEFAULT '0';`

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

`ALTER TABLE audit_trail CHANGE gl_date gl_date DATE NULL DEFAULT NULL;`

**Comment by wildanm** [comment]
Jalankan SQL berikut :

`ALTER TABLE audit_trail CHANGE user user BIGINT(20) NOT NULL DEFAULT '0';`

**Comment by wildanm** [comment]
Done. 

Silahkan jalankan SQL nya di semua instalasi Tirta ERP, jika sudah, tolong tutup issue ini
