### ISSUE TITLE
Dibuatkan fungsi transfer untuk perpindahan konsumen beda depot

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#162]
Data yg ditransfer data pelanggan, penjualan, pinjaman gallon

**Comment by wildanm** [comment]
Ada beberapa pertanyaan : 

1. Di depot asal, apakah data pelanggan tersebut dihapus ? 
2. Apakah jadwal kirim pelanggan tersebut ikut ditransfer ?

**Comment by wildanm** [comment]
Transfer data ini agak kompleks, karena data pelanggan itu berhubungan ke banyak tabel.

**Comment by albeth** [comment]
ya jadwal ditransfer juga.....jangan dihapus kodenya tapi kalau bisa berubah non aktif dan ada dikasih ket pindah depotnya sebab kalau dihapus takut kaya muarakarang

**Comment by wildanm** [comment]
Ada masasalah, coba perhatian tbl_jadwal, dia primary key nya seperti ini : 

B200000003 

Kalau ditransfer seadanya, kemungkinan bentrok dengan cno_jadwal di depot tujuan, kalau dibuat cno_jadwal baru, kalau di transfer nanti akan  numpul datanya dengan cno_jadwal untuk ckode_customer dari depot sebelumnya.

**Comment by albeth** [comment]
depot tujuan bukannya beda kode dan

**Comment by wildanm** [comment]
Yang ke copy kan history nya  (data sebelumnya di depot asal)

**Comment by albeth** [comment]
kalau misalnya semua data pindah ke depot baru datanya kecuali kodenya aja yg masih ada didepot lama gmn?

**Comment by wildanm** [comment]
Ini asumsinya depot lama dan baru ada di komputer yang berbeda ya. 

Maksudnya,  kode apa yang masih ada di depot lama ?

**Comment by albeth** [comment]
kode konsumennya dan

**Comment by wildanm** [comment]
Nanti pas tranfer bentrok di tirta erp pusatnya. 

Fitur transfer konsumen antar depot ini sifatnya cut and paste bukan copy and paste.

**Comment by albeth** [comment]
dibuat seperti muara karang dan itukan beda komputernya sama kode depotnya

**Comment by wildanm** [comment]
Kalau pindah kayak muara karang, itu cut and paste. Di depot asal semua datanya dihapus.

**Comment by albeth** [comment]
ohhh gt tapi nanti pas penambahan konsumen bisa double gak kodenya dan?

**Comment by albeth** [comment]
kaya dulu dan....udah pindah kode depotnya ke mk....trus pas nambah kode baru dilodan kodenya sama kaya yg pindah ke mk...jdnya datanya di ps baru double

**Comment by wildanm** [comment]
Gak. Kemarin bugs yg itu udah dibenerin. Nanti coba aja. 

Coba update erp nya, 

di menu  : http://tirtaerp.np/masterdata/customers# ( ganti url erp nya sesuai dgn yg disana), yang baru jalan menu export, untuk uji coba awal aja, itu kode depot tujuannya belum diubah. 

Ekstrak file transfer nya. Kurang lebih seperti itu, mesti dianalisa lagi, dibuat schema, tabel mana saja yg berhubungan dgn tbl_customer.

**Comment by albeth** [comment]
iya dan datanya yg mau di transfer sesuai dengan di zip

**Comment by albeth** [comment]
itu baru export aja yah?

**Comment by wildanm** [comment]
Iya. Masih perlu analisa lagi tabel mana aja yg perlu diimport

Pada tanggal 22 Jul 2016 1:42 PM, "albeth" <notifications@github.com>
menulis:

**Comment by albeth** [comment]
kira2 bisa digunain kapan dan? sebab i mau pindahin yg 3 konsumen kmrn itu dan.....inputan pinjamannya udah numpuk...udah kirim dari pabrik per april

**Comment by wildanm** [comment]
Malam ini coba dianalisa lagi, input mah lanjutin aja di depot yg skrg, yg
lama... nanti kan tinggal pindah ?

Pada tanggal 22 Jul 2016 2:17 PM, "albeth" <notifications@github.com>
menulis:

**Comment by wildanm** [comment]
![tbl_customer](https://cloud.githubusercontent.com/assets/462398/17073973/38394638-50a0-11e6-9618-090b2586933b.png)

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

`INSERT IGNORE INTO tbl_statuscust(ckode_statuscust, cketerangan) values('T','Transfer') ;`

**Comment by wildanm** [comment]
TODO : 

1. Validasi konten file dalam zip apakah lengkap ? 
2. Validasi impor

**Comment by wildanm** [comment]
Done, 6e83916 (bitbucket)
