### ISSUE TITLE
dibuat tools perubahan harga 

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#171]
1. Harga lama dibuat dropdown, isinya harga apa saja yang ada di tbl_jadwal untuk kode produk tersebut
2. Preview : List, konsumen mana saja yang harga produk nya berubah ? 
3. Proses

**Done**
1.  ocean 11.000 ke 12.000 : kode produk 11005
2. gin 11.000 ke 12.000 : kode produk : 11004
2. ws       12.000 ke 13.000 : kode produk 11001

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

```
update tbl_jadwal set nharga_satuan=12000 where ckode_produk=11005 and nharga_satuan=11000 ;

 update tbl_jadwal set nharga_satuan=13000 where ckode_produk=11001 and nharga_satuan=12000 ;

```

**Comment by wildanm** [comment]
Partially done in, 11f8cc8 (bitbucket)

**Comment by wildanm** [comment]
Done in 1534003 (bitbucket). 

Utilitas untuk perubahan harga dapat diakses di menu : Utilitas > Distribusi > Perubahan Harga
