### ISSUE TITLE
Ditambah kolom created_at, updated_at, created_by, updated_by di tabel tbl_kendaraan

### ISSUE THREAD

**Issue by wildanm** [OpenThink-Labs/TirtaERP#174]

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

`ALTER TABLE `tbl_kendaraan` ADD `created_at` DATETIME NOT NULL AFTER `ctransfer`, ADD `updated_at` DATETIME NOT NULL AFTER `created_at`, ADD `created_by` BIGINT NOT NULL AFTER `updated_at`, ADD `updated_by` BIGINT NOT NULL AFTER `created_by`;`

**Comment by wildanm** [comment]
Done in 	 a4149d6  (bitbucket)

**Comment by wildanm** [comment]
Ini sudah dijalanin semua ?

**Comment by albeth** [comment]
blom dan....komp mk blom nti kalau udah i close
