### ISSUE TITLE
pilihan jenis bayar sumbangan,promosi, sample seharusnya tidak masuk dalam print tagihan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#176]

**Comment by wildanm** [comment]
URL untuk penagihan nya tolong ditulis.

**Comment by albeth** [comment]
http://erp2012.tirta/reports/faktur/penagihan/per/pelanggan dan http://erp2012.tirta/reports/faktur/penagihan/per/rute

**Comment by wildanm** [comment]
Done in 8fb5ce1 (bitbucket)
