### ISSUE TITLE
Ditambah kolom created_at, updated_at, created_by, updated_by di tabel tbl_botoljaminan

### ISSUE THREAD

**Issue by wildanm** [OpenThink-Labs/TirtaERP#179]

**Comment by wildanm** [comment]
Jalankan SQL ini di semua instalasi Tirta ERP : 

`ALTER TABLE `tbl_botoljaminan` ADD `created_at` DATETIME NOT NULL AFTER `ctransfer`, ADD `updated_at` DATETIME NOT NULL AFTER `created_at`, ADD `created_by` BIGINT NOT NULL AFTER `updated_at`, ADD `updated_by` BIGINT NOT NULL AFTER `created_by`;`

**Comment by wildanm** [comment]
Done in e1d6f01 (bitbucket)

**Comment by wildanm** [comment]
Ini sudah dijalanin semua ?

**Comment by albeth** [comment]
blom dan....komp mk blom nti kalau udah i close
