### ISSUE TITLE
posting otomatis untuk jurnal accounting, pabrik dan penagihan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#197]
1. Pabrik, http://tirtaerp.np/utilities/tirtamurni/posting

2. Accounting, http://tirtaerp.np/accounting/posting

**Comment by wildanm** [comment]
Untuk 1 dan 2 sudah di (db91df1) bitbucket. 

Hanya saja, agar dapat berjalan otomatis, cron harus diupdate. 

Lihat instalasi bagian cron : 

http://tirtaerp.openthinklabs.com/2015/01/instalasi-dan-update.html

**Comment by wildanm** [comment]
Done
