### ISSUE TITLE
bisa diset zoom pdf nya

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#223]
1. http://erp2012.tirta/reports/harian/mobil **Done**
2. http://erp2012.tirta/reports/daily/sales/per/invoice/payment/type **Done**
3. http://erp2012.tirta/reports/monthly/delivery/amdk/per/customer **Done**
4. http://erp2012.tirta/reports/recap/monthly/sales/per/vehicle **Done**
5. http://erp2012.tirta/reports/recap/monthly/sales/per/product **Done**
6. http://erp2012.tirta/reports/daily/sales/per/invoice/payment/type#  **Done**

**Comment by wildanm** [comment]
Done in 7b3eea3 (bitbucket)
