### ISSUE TITLE
bisa diset zoom pdf nya tambahan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#224]
1. http://erp2012.tirta/reports/monthly/delivery/amdk/pabrik/per/customer
2. http://erp2012.tirta/reports/recap/monthly/sales/pabrik/per/vehicle
3. http://erp2012.tirta/reports/recap/monthly/sales/pabrik/per/product
4. http://erp2012.tirta/reports/daftar/tagihan/per/rute
5. http://erp2012.tirta/transactions/bottle/loans

**Comment by wildanm** [comment]
Done Changeset: | 1389 (44469771c103) 

Jika sudah Ok, close
