### ISSUE TITLE
transfer botol pinjaman metodenya drop/insert

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#233]

**Comment by wildanm** [comment]
Setelah dipelajari, pendekatan  https://github.com/OpenThink-Labs/TirtaERP/issues/232 sudah benar.

Tinggal perlu reset diawal saja. 

Di Depot pasar baru jalankan SQL ini untuk menghapus data botol pinjaman selurh pelanggan depot pabrik,

Jalankan di Tirta ERP Pasar Baru :

`DELETE FROM tbl_botoljaminan WHERE ckode_customer IN(SELECT ckode_customer FROM tbl_customer WHERE ckode_depot IN('B20','F13','G13','O13'));


Lalu jalankan SQL ini di Tirta ERP pabrik, 

`UPDATE tbl_botoljaminan set ctransfer="Y" ;`
`

**Comment by wildanm** [comment]
Reset botol pinjaman lodan : 

Jalankan SQL ini di Tirta ERP Pasar Baru : 

`DELETE FROM tbl_botoljaminan WHERE ckode_customer IN(SELECT ckode_customer FROM tbl_customer WHERE ckode_depot IN('U10','O10','G10'));`

Lalu jalankan SQL ini di Tirta ERP Lodan :

`UPDATE tbl_botoljaminan set ctransfer="Y" ;`

**Comment by wildanm** [comment]
Reset botol pinjaman tangerang : 

Jalankan SQL ini di Tirta ERP Pasar Baru : 

`DELETE FROM tbl_botoljaminan WHERE ckode_customer IN(SELECT ckode_customer FROM tbl_customer WHERE ckode_depot IN('B10','O12'));`

Lalu jalankan SQL ini di Tirta ERP Tangerang :

`UPDATE tbl_botoljaminan set ctransfer="Y" ;`

Transfer ulang data tangerang
