### ISSUE TITLE
dibuat fungsi close dan open pake user wildan perkonsumen perbulan di umur piutang supaya kaga muncul yg data konsumen sudah tidak atau ada masalh pembayaran

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#240]

**Comment by wildanm** [comment]
Jalankan SQL berikut disemua instalasi tirta erp: 

`CREATE TABLE faktur_bermasalah (cnofaktur VARCHAR(15), catatan VARCHAR(255), created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, created_by BIGINT, updated_by BIGINT, INDEX created_by_idx (created_by), INDEX updated_by_idx (updated_by), PRIMARY KEY(cnofaktur, catatan)) ENGINE=InnoDB DEFAULT CHARSET=latin1;`

```
ALTER TABLE faktur_bermasalah ADD CONSTRAINT faktur_bermasalah_updated_by_sf_guard_user_id FOREIGN KEY (updated_by) REFERENCES sf_guard_user(id) ON DELETE CASCADE;
ALTER TABLE faktur_bermasalah ADD CONSTRAINT faktur_bermasalah_created_by_sf_guard_user_id FOREIGN KEY (created_by) REFERENCES sf_guard_user(id) ON DELETE CASCADE;
ALTER TABLE faktur_bermasalah ADD CONSTRAINT faktur_bermasalah_cnofaktur_tbl_sales_h_cnofaktur FOREIGN KEY (cnofaktur) REFERENCES tbl_sales_h(cnofaktur);
```

**Comment by wildanm** [comment]
Partially done in 09e53e1. 

Tinggal fungsi edit/hapus faktur bermasalah

**Comment by albeth** [comment]
Kok ada fungsi edit faktur bermasalah dan?

**Comment by wildanm** [comment]
Yg di edit catatan-nya.

**Comment by albeth** [comment]
Ohhh gt

**Comment by wildanm** [comment]
Done in 46bba7b

**Comment by wildanm** [comment]
Kalau sudah ok, close ya. 

SQL nya harus dijalankan di semua instalasi Tirta ERP
