### ISSUE TITLE
Penyempurnaan fungsi gabungkan data pelanggan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#267]
Data pelunasan ikut digabungkan

Gabungkan data pelanggan ini: 

B20wei00001 ke B10wei00001                        
B20bar00001 ke B10bar00002                        
U10hom00001 ke u10mim00019                        
U10lia00020 ke u10lia00019

**Comment by wildanm** [comment]
Done 7971ef3 . 

Gunakan fitur gabungkan pelanggan di data master pelanggan, yg skrg sudah disempurnakan. 

Silahkan tutup issue ini juga sudah ok.
