### ISSUE TITLE
dibuatkan menu laporan mutasi bank (masukin dilist laporan-receivable)

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#278]
dibuatkan rincian laporan per no rekening bank perpelunasan - pertanggal setor - perjenis bayar.

pilihan menunya 
- kode akun(nomor rekening bank dipelunasan)
[MUTASI BANK.xlsx](https://github.com/OpenThink-Labs/TirtaERP/files/725920/MUTASI.BANK.xlsx)
- periode dari ke tgl brp
- jenis bayar bisa satu atau seluruhnya
- kode pelanggan bisa satu atau seluruhnya

hasil laporan cetaknya sesuai attach excel

**Comment by wildanm** [comment]
Tolong buatkan contoh excel hasil output laporannya.

**Comment by wildanm** [comment]
Ini di Menu Laporan --> Receivable ?

**Comment by albeth** [comment]
itu excelnya diatas MUTASI BANK.xlsx

**Comment by albeth** [comment]
![screenshot from 2017-01-24 15 36 08](https://cloud.githubusercontent.com/assets/17263267/22239844/d917f252-e24a-11e6-9988-ea7468b85dca.png)

**Comment by wildanm** [comment]
Partially done in 43ea3f7

Coba update, seperti itu bukan  ?

**Comment by albeth** [comment]
ya dan.....cuma minta tolong ditambah
1. jadi satu aja perpelanggan list fakturnya cuma bisa diklik liat rinciannya di jumlah pelunasannya
2. ditambahkan kolom JENIS PEMBAYARAN sebelum jumlah pelunasan
3. disort pertanggal setoran
4. ditambahkan lagi kolom total dipaling kanan setelah pelunasan...tapi dia nilai totalnya perhitungannya: misalnya ada 3 transaksi....jd nilai total baris pertama = jumlah pelunasan baris pertama...trus baris ke 2 totalnya = total baris pertama + jumlah pelunasan baris ke 2....total baris ke 3= total baris ke 2 + jumlah pelunasan baris 3

**Comment by wildanm** [comment]
Kalau ada pelanggan tanggal setor nya berbeda, laporannya di satukan  atau dipisah ?

**Comment by albeth** [comment]
dipisah dan sesuai tanggal setor aja

**Comment by wildanm** [comment]
Done in 7b73103. 

Silahkan periksa, kalau sudah Ok, close ya.

**Comment by albeth** [comment]
dan ada yg mash kurang
1. nilai di jumlah pelunasannya bisa diklik buat liat detail rincian faktur yg dilunasin
2. ditambahkan lagi kolom total dipaling kanan setelah jumlah pelunasan...tapi dia nilai totalnya perhitungannya: misalnya ada 3 transaksi....jd nilai total baris pertama = jumlah pelunasan baris pertama...trus baris ke 2 totalnya = total baris pertama + jumlah pelunasan baris ke 2....total baris ke 3= total baris ke 2 + jumlah pelunasan baris 3
3. hasil cetak pdf disort tanggalnya terbalik seharusnya dari 1 ke terakhir

**Comment by wildanm** [comment]
Done. in 212351e. 

Silahkan update, kalau suda Ok, close ya.

**Comment by albeth** [comment]
1. masih blom sesuai seharusnya jumlah pelunasan dibawah sama dengan jumlah total tapi itu kaga sama
2. jumlah data yg ditampilkan selalu kurang satu data

**Comment by wildanm** [comment]
Coba screenshotnya


Pada tanggal 3 Feb 2017 16:37, "albeth" <notifications@github.com> menulis:
