### ISSUE TITLE
transfer dut ke water yg semua jumlah datanya 0 masih ke transfer ke water

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#279]

**Comment by wildanm** [comment]
Harusnya sih sudah tidak. Coba lagi. 

Kalau sudah Ok, close

**Comment by albeth** [comment]
![screenshot from 2017-02-02 12 25 15](https://cloud.githubusercontent.com/assets/17263267/22538110/8ef04f54-e942-11e6-9c01-cd3674bc678c.png)
udah didelete muncul lagi

**Comment by wildanm** [comment]
Coba kirim ulang lagi transferan dari distribusi yg terbaru

Pada tanggal 2 Feb 2017 12:24, "albeth" <notifications@github.com> menulis:

**Comment by wildanm** [comment]
Done in 
Changeset:
1192 (8f711776b3a9). 

Ternyata selama ini data nbotol_kosong tidak ter transfer ke water, kalau data jumlah galong kosong mau ditransfer ke water semuanya,  harus jalanin transfer dut ke water dari tanggal paling awal. 

Close kalau sudah ok
.

**Comment by albeth** [comment]
dan ini kan datanya kaga mau ditransfer ke water yg kirim dan kosongnya = 0

**Comment by wildanm** [comment]
Iya memang begitu.

Yg sebelum diperbaiki, meskipun galon kosong ada data, jumlah kirim ada
data, data yg ketransfer cuman jumlah kirim aja, jumlah botol kosong gak
ditransfer

Pada tanggal 7 Feb 2017 12:12, "albeth" <notifications@github.com> menulis:
