### ISSUE TITLE
view all blom ke view semua

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#282]
1. http://erp2012.tirta/transactions/sales/invoice (yg faktur bermasalah)
2. http://erp2012.tirta/transactions/sales (yg faktur bermasalah)

**Comment by wildanm** [comment]
Done in c604f64. 

Jika sudah Ok, close ya

**Comment by albeth** [comment]
dan knp jumlah faktur bermasalah tidak sama dengan jumlah detailnya

![screenshot from 2017-01-30 10 08 53](https://cloud.githubusercontent.com/assets/17263267/22411266/83830f0a-e6d4-11e6-89ea-6482200ea9b8.png)

**Comment by wildanm** [comment]
Sudah diperbaiki di 92cd5fa
