### ISSUE TITLE
tidak bisa lihat laporan atau proses

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#288]
1. http://erp2012.tirta/reports/monthly/delivery/amdk/pabrik/per/customer
2. http://erp2012.tirta/reports/recap/monthly/sales/pabrik/per/vehicle

**Comment by wildanm** [comment]
Done 

Changeset:
1183 (a2dc10eeafcc) 

Silahkan update. close jika sudah Ok

**Comment by albeth** [comment]
masih blom bisa dan yg pabrik punya

**Comment by albeth** [comment]
blom bisa dan

**Comment by wildanm** [comment]
Coba update. Screenshot kalau masih tidak bisa, di i gak masalah soalnya

**Comment by albeth** [comment]
Yg pabrik dan

**Comment by albeth** [comment]
http://erp2012.tirta/reports/recap/monthly/sales/pabrik/per/product blom bisa

**Comment by wildanm** [comment]
Sudah, coba update.
