### ISSUE TITLE
Pindah data

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#318]
1. Pindah data pelunasan B20 O13 F13 dan G13 dari komp ps baru ke komp pabrik
2. Data pelunasan ikut ditransf ketika transf data dari pabrik ke komp ps baru

**Comment by wildanm** [comment]
Changeset:
1227 (0d45dfb1528f) Data pelunasan ikut ditransfer dari distribusi, https://github.com/OpenThink-Labs/TirtaERP/issues/318

**Comment by wildanm** [comment]
SQL untuk transfer data pelunasan : 

`mysqldump --lock-all-tables -u root -p --no-create-info --complete-insert --disable-keys tirtaerp2012 tbl_cash_h --where="ckode_from IN(SELECT ckode_customer FROM tbl_customer WHERE ckode_depot IN('B20','O13','F13','G13'))" > tbl_cash_h.sql
`
`mysqldump --lock-all-tables -u root -p --no-create-info --complete-insert --disable-keys tirtaerp2012 tbl_cash_d --where="cno_receipt IN(SELECT cno_receipt FROM tbl_cash_h WHERE ckode_from IN(SELECT ckode_customer FROM tbl_customer WHERE ckode_depot IN('B20','O13','F13','G13')))" > tbl_cash_d.sql`

**Comment by wildanm** [comment]
Done, jika sudah Ok, close.
