### ISSUE TITLE
Dibuat kolom tbl_sales_h.dtanggal_pelunasan

### ISSUE THREAD

**Issue by wildanm** [OpenThink-Labs/TirtaERP#322]
Dibuat kolom tbl_sales_h.dtanggal_pelunasan. 

Tanggal ini otomati diupdate ketika proses pelunasa dilakukan. 

Digunakan salah satunya di sort laporan mutasi piutang. 

http://erp2012.tirta/reports/mutasi/piutang

**Comment by wildanm** [comment]
Kok ditutup ? Ini gak perlu di sort ?

Pada tanggal 20 Mar 2017 17:01, "albeth" <notifications@github.com> menulis:

**Comment by albeth** [comment]
saya pikir yg sebelumnya

**Comment by wildanm** [comment]
Ini link nya yg mana ya ....? lupa saya..

**Comment by albeth** [comment]
Mutasi hutang yah....yg di receivable

**Comment by albeth** [comment]
http://erp2012.tirta/reports/mutasi/piutang

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

`ALTER TABLE tbl_sales_h  ADD  dtanggal_pelunasan  DATE NULL DEFAULT NULL AFTER  dtanggal;`

**Comment by wildanm** [comment]
Jalankan perintah : 

`./symfony tirtaerp:tirtaerp:issue322`

**Comment by wildanm** [comment]
Jalankan SQL untuk membuat trigger berikut ini : 

DROP TRIGGER IF EXISTS tbl_cash_d_on_insert;
DELIMITER $$
CREATE  TRIGGER tbl_cash_d_on_insert
AFTER INSERT ON `tbl_cash_d` FOR EACH ROW
BEGIN
   DECLARE vdtanggal date;

   SELECT dtanggal INTO @vdtanggal FROM tbl_cash_h
   WHERE cnofaktur = NEW.cnofaktur ;

   IF @vdtanggal != ''
   THEN
     UPDATE tbl_sales_h
     SET dtanggal_pelunasan = @vdtanggal
     WHERE cnofaktur = NEW.cnofaktur;
  END IF ;

END;
$$
DELIMITER ;


DROP TRIGGER IF EXISTS tbl_cash_h_on_update;
DELIMITER $$
CREATE  TRIGGER tbl_cash_h_on_update
AFTER UPDATE ON `tbl_cash_h` FOR EACH ROW
BEGIN
   DECLARE vdtanggal date;
   DECLARE vcnofaktur varchar(15);

   SELECT dtanggal INTO @vdtanggal FROM tbl_cash_h
   WHERE cno_receipt = NEW.cno_receipt ;

   SELECT cnofaktur INTO @vcnofaktur FROM tbl_cash_d
   WHERE cno_receipt = NEW.cno_receipt;

   IF @vdtanggal != ''
   THEN
     UPDATE tbl_sales_h
     SET dtanggal_pelunasan = @vdtanggal
     WHERE cnofaktur = @vcnofaktur;
  END IF ;

END;
$$
DELIMITER ;

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

TABLE `tbl_sales_h` ADD INDEX(`dtanggal`);

**Comment by wildanm** [comment]
@albeth  laporan ini urutannya nya mau seperti apa ya ? 

http://erp2012.tirta/reports/mutasi/piutang

**Comment by wildanm** [comment]
Laporan diurutkan dari tanggal pelunasan terbaru. 

Done in 
Changeset:
1298 (309d731efb0b)

Jika sudah Ok, close
