### ISSUE TITLE
http://erp2012.tirta/transactions/receipt/kredit---- ada pelunasan yg gantung tapi di aged tidak muncul dan dipelunasan sudah ada no BM nya

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#329]
no konsumen yg bermasalah
1. u10dam00001
2. u10dar00013
3. u10fen00005
4. u10cok00001
5. u10kan00025
6. u10anu00019

**Comment by wildanm** [comment]
Done in 
Changeset: 1234 (40357e22db31)

Melalui terminal : 

1. Masuk ke folder instalasi Tirta ERP 

cd /home/www/TirtaERP2012 

2. lalu jalankan perintah berikut : 

./symfony tirtaerp:perbaiki-kepemilikan-faktur-pelunasan 


Kalau sudah selesai, coba lihat lagi, pelunasan kredit dan tunai, apa faktur2 yg sudah lunas masih muncul lagi ?

Seharusnya tidak, dan tidak perlu melakukan rekonsiliasi ulang dari awal lagi.
