### ISSUE TITLE
Melihat list pelunasan double

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#330]

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

`CREATE TABLE faktur_terlunasi_lebih_dari_sekali (cnofaktur VARCHAR(15), catatan VARCHAR(255), created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, created_by BIGINT, updated_by BIGINT, INDEX created_by_idx (created_by), INDEX updated_by_idx (updated_by), PRIMARY KEY(cnofaktur, catatan)) ENGINE = INNODB;`

**Comment by wildanm** [comment]
Partially done 
Changeset: 1236 (36dfdcd0b385)

**Comment by wildanm** [comment]
Untuk memeriksa jika ada pelunasan berlebih bisa periksa per depot dengan perintah : 

(masuk ke folder instalasi Tirta ERP dulu) lalu jalankan:

`./symfony tirtaerp:periksa-faktur-terlunasi-lebih --ckode-depot=U10`

Atau jika ingin memeriksa seluruh depot sekaligus (waktu running akan lebih lama), jalankan : 

`./symfony tirtaerp:periksa-faktur-terlunasi-lebih --is-all=1 `

**Comment by wildanm** [comment]
Dicoba dulu, laporan faktur pelunasan berlebih bisa dilihat di : 

http://erp2012.tirta/reports/aged/receivable

JIka ada yg berlebih, metode memperbaikinya, ingin diedit atau dihapus ?

**Comment by wildanm** [comment]
Done 
Changeset: 1237 (87be5cc27e7e) 

Bisa diedit. 

Jika sudah Ok, close
