### ISSUE TITLE
otomatis jalankan perintah untuk pelunasan double bisa set tgl mulai kapan dan bisa perkonsumen

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#331]

**Comment by wildanm** [comment]
Done 
Changeset: 1252 (d1764445a688) 

Cron entrinya perlu diupdate. 

Ingin dijalankan setiap berapa lama ?

**Comment by albeth** [comment]
1bulan sekali tgl setiap tgl 1

**Comment by wildanm** [comment]
Ini sudah di set ya cron nya.
