### ISSUE TITLE
http://tirtaerp.lodan/reports/daily/sales/per/vehicle/berdasarkan/faktur

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#339]
jika ada inputan hanya gallon kosong saja tidak muncul di cetak

**Comment by wildanm** [comment]
I coba muncul kok ya ...

**Comment by albeth** [comment]
Coba nanti sekalian team u coba yah dan

**Comment by wildanm** [comment]
U yg coba aja kalau yg ini, screenshot nya kirim, nomor faktur mana yg gak
muncul

Pada tanggal 25 Apr 2017 07:57, "albeth" <notifications@github.com> menulis:

**Comment by albeth** [comment]
bisa dan
