### ISSUE TITLE
http://tirtaerp.lodan/transactions/invoicing/process

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#353]
"tanggal jadwal kirim" dirubah jd "hari kirim" dan pemilihannya dirubah jadi bentuk harian (minggu,senin,selasa,rabu,kamis,jumat,sabtu)

**Comment by wildanm** [comment]
Tetap harus menggunakan tanggal, tapi bahasa di Kalender nya sudah diganti menggunakan bahasa Indonesia.
