### ISSUE TITLE
seluruh kode depot muncul (yg status aktif dan non aktif) diseluruh user

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#355]
1. http://erp2012.tirta/reports/monthly/delivery/amdk/per/customer
2. http://erp2012.tirta/reports/recap/monthly/sales/per/product
3. http://erp2012.tirta/reports/recap/monthly/sales/per/vehicle
4. http://erp2012.tirta/reports/aged/receivable

**Comment by wildanm** [comment]
Coba cek data master depotnya, pastikan benar non aktif ..?

Screeshot data master depot dan screnshoot yg tidak aktif tapi tetap muncul. 

I periksa, sudah tidak muncul soalnya

**Comment by albeth** [comment]
ini maksudnya tetap muncul dan walaupun sudah tidak aktif

**Comment by wildanm** [comment]
Done 
Changeset: 1289 (4f33a8a73075) 

Nomor 4 tidak ada opsi depot kan ? 

Jika sudah Ok,close
