### ISSUE TITLE
Transfer Data Dari Depot via Disk ditambah opsi seluruh data botol jaminan

### ISSUE THREAD

**Issue by wildanm** [OpenThink-Labs/TirtaERP#377]

**Comment by wildanm** [comment]
@albeth setelah dilihat, defaultnya sudah seluruh botol jaminan di transfer, coba kirim data transfer yg gak semua tertranfser, yg gak ada apa ? yg di wa kemarin kirim ke email sekalian dgn file transfernya

**Comment by albeth** [comment]
contoh : u10tra00006

**Comment by wildanm** [comment]
Ini sudah kan ya  ?
