### ISSUE TITLE
print bon pengiriman dan penagihan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#386]
diset alamatnya panjangnya sesuai kebutuhan setelah itu diprintnya turun kebawah jd tidak panjang melewati bon cetakannya...contoh kode O10BER00007

**Comment by wildanm** [comment]
@albeth URL-URL nya mana ...

**Comment by wildanm** [comment]
Done in 
Changeset:
1314 (75647a725c7d) 

Jika sudah Ok, close

**Comment by albeth** [comment]
http://tirtaerp.lodan/reports/print/invoice/delivery
http://tirtaerp.lodan/reports/faktur/penagihan/per/pelanggan
http://tirtaerp.lodan/reports/faktur/penagihan/per/rute

**Comment by wildanm** [comment]
Done 
Changeset:
1315 (f8fc664d6c55)

**Comment by wildanm** [comment]
Silahkan dicoba lagi
