### ISSUE TITLE
transfer data

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#397]
1. transfer data dari komputer lodan ke ps baru....yg kode konsumennya dirubah tidak niban ke komputer ps baru
2. transfer data dari komputer lodan ke ps baru.....jika jumlah kirim dan botol kosongnya dirubah nilainya jadi nol semua trus ditransfer ke komputer pasarbaru datanya tidak niban juga
3. transfer dari komputer lodan ke ps baru nilai yg nol jumlah kirim dan kosongnya tetep ditransfer

**Comment by wildanm** [comment]
2 dan 3 sudah Ok, yang 1 memang tidak bisa ...
