### ISSUE TITLE
langsung terpilih jenis produknya tapi yg muncul yg hanya ada inputan jumlah kirim dan botol kosongnya

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#409]
1. http://erp2012.tirta/reports/daily/sales/per/invoice/payment/type
2. http://erp2012.tirta/reports/daily/sales/per/vehicle/berdasarkan/faktur

**Comment by wildanm** [comment]
Maksudnya ini bagaimana ?

**Comment by albeth** [comment]
kadang2 kaga ada inputannya tetep kepilih dan produknya

**Comment by wildanm** [comment]
Maksudnya ? kan produknya kita milih sendiri (untuk yg nomor 1). 

Nomo 2, harus jelas contohnya, di form nya milih apa aja ? kirim screenshot yg produknya kepilih tapi gak ada inputan

**Comment by wildanm** [comment]
Yang no 2 sudah diupdate, silahkan dicoba. 
Changeset: | 1343 (49f5b3ad2db2) 

Yang nomor 1 belum ada fungsi otomatis pilih produk yg sudah ada inputnya
