### ISSUE TITLE
http://tirtaerp.lodan/masterdata/customers#

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#414]
transfer data pelanggan antar depot bisa tanpa data penjualan karena jika dibandingkan di http://erp2012.tirta/reports/perbandingan/surat/jalan/puso/dan/faktur/untuk/pelanggan hasilnya jd tidak sama

**Comment by wildanm** [comment]
Bukan tanpa data penjualan, tapi dengan data penjualan, tapi data penjualan nya tidak dihapus.

**Comment by wildanm** [comment]
Setelah dilihat, yg sekarang data penjualannya memang tidak dihapus, tetap ada .... 

Ini maksudnya transfer dari depot lain ke pabrik ya ...?

**Comment by wildanm** [comment]
Done in Changeset: | 1347 

Jika sudah Ok, close
