### ISSUE TITLE
Dibuatkan fungsi close untuk pelunasan dan fungsi open untuk user wildan/administrator

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#417]

**Comment by wildanm** [comment]
Jalankan SQL berikut disemua instalasi Tirta ERP : 

`ALTER TABLE tbl_cash_h ADD is_closed TINYINT(1) NULL DEFAULT '0' AFTER cid;`

**Comment by wildanm** [comment]
Done in Changeset: | 1351 (728f3b26d557). 

Jika sudah Ok, close
