### ISSUE TITLE
dibuat perbandingan hasil laporan http://tirtaerp.lodan/transactions/stock/handover/amdk/back/home dengan http://tirtaerp.lodan/reports/recap/monthly/sales/per/vehicle

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#418]
1. yg dibandingan "jumlah penjualan agen ditambah penjualan user per no polisi" di http://tirtaerp.lodan/transactions/stock/handover/amdk/back/home dengan "qty di penjualan perkendaraan per no polisi" http://tirtaerp.lodan/reports/recap/monthly/sales/per/vehicle.
2. yg dibandingan "penjualan cash per no polisi" di http://tirtaerp.lodan/transactions/stock/handover/amdk/back/home dengan "kolom tunai per no polisi" http://tirtaerp.lodan/reports/recap/monthly/sales/per/vehicle.
3. Pilihan depot dihilangkan

**Comment by wildanm** [comment]
Se, yg di Menu Validasi Data: 

http://tirtaerp.lodan/utilities/validate/the/data

Sepertinya ini hanya untuk dijalankan di lodan ya ? Kedua validasi diatas mau ditempatkan di menu ini ?

**Comment by albeth** [comment]
Boleh dan

**Comment by wildanm** [comment]
Bukannya udah ada ya ? Yang pertama sama dengan : Jumlah pengiriman setiap mobil dalam satu hari harus sama dengan jumlah yg diinput di penjualan

Yang kedua sama dengan yg ini : Jumlah uang tunai setiap mobil dalam satu hari harus sama dengan jumlah yg nilai tunai yg ada di penjualan 

Sudah ada di : http://tirtaerp.lodan/utilities/validate/the/data

**Comment by wildanm** [comment]
Tampilannya sedikit diperbaiki. 

Kalau itu sudah benar, close ya

**Comment by wildanm** [comment]
Opsi depot depot dibuang, Done in Changeset: | 1366 (6c78336b99ea) Done 

Jika sudah Ok, close

**Comment by albeth** [comment]
1. Data per nopol yg nilai pengiriman dan penjualan= 0 tidak muncul
2. Pilhan tanggalnya dibuat bisa lebidari sehari (dari ke)

**Comment by wildanm** [comment]
Sudah diupdate, Changeset: | 1367 (e05050e7f412) 
Kalau sudah Ok, close
