### ISSUE TITLE
http://erp2012.tirta/reports/insentif# Laporan Kunjungan Pengemudi Ke Konsumen

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#422]
1. klau milih perpelanggan satu2 kaga muncul laporannya
2. sama hasil laporannya minta ditambahkan keterangan kolom nama pelanggan sebelum kolom uang jalan

**Comment by wildanm** [comment]
Done in Changeset: | 1360 (d898633dab49)
