### ISSUE TITLE
Ditambahkan status pelanggan "BERMASALAH"

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#423]
1. tidak muncul bon kiriman pelanggan tersebut ketika proses faktur didistribusi
2. jika ada penggambilan konsumen/bon penjualan ditanggal tertentu tetap ke transfer dari distribusi ke dut
3. tetap muncul dirute penagihan dan bisa cetak bon tagihan

**Comment by wildanm** [comment]
Jalankan SQL ini di semua instalasi Tirta ERP : 

`INSERT IGNORE INTO tbl_statuscust VALUES('M','Bermasalah');`

**Comment by wildanm** [comment]
Done in Changeset: | 1359 (b1a616136af3) 

Jika sudah Ok, close
