### ISSUE TITLE
jadwal kirim harian bisa diurutkan susunan bon kirimannya

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#426]

**Comment by wildanm** [comment]
Ini maksudnya gimana ?

**Comment by albeth** [comment]
jd gini....klau sekarang ketika kita proses faktur itukan ada jumlah bon yg muncul.....klau skrg itu print bon kiriman itu berdasarkan kode konsumen per abjad.....nah itu kedepan sy mau susun print bon kiriman hasil printnya bonnya keluar urutannya sesuai dengan anak2 rute kirim sesuai dilapangan

**Comment by wildanm** [comment]
Ini URL nya yg mana .. ?

**Comment by wildanm** [comment]
Done in 

Changeset: | 1399 (36600b34baac)

Jika sudah Ok, close
