### ISSUE TITLE
dibuatkan laporan pelunasan gallon pinjaman seperti http://erp2012.tirta/reports/mutasi/bank

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#427]

**Comment by wildanm** [comment]
Muta per pelanggan sudah, jadi di laporan ada 2 tab, 1 untuk pelunasan penjualan, 1 lagi untuk pelunasan ujb. 

Untuk per refference dan versi cetaknya belum.

**Comment by wildanm** [comment]
Update Changeset: | 1375 (3f064db09126) 

Yang belum versi cetak dan klik detail.

**Comment by wildanm** [comment]
Done in Changeset: | 1383 (104e712cc756) 

Jika sudah Ok, close
