### ISSUE TITLE
http://tirtaerp.lodan/reports/laporan/pelanggan/absen/n/bulan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#429]
yg muncul hanya yg statusnya aktif dan baru

**Comment by wildanm** [comment]
Done in Changeset: | 1376 (fbe25f469029) 

Jika sudah Ok, close

**Comment by albeth** [comment]
jika jumlah kirim dan kosong = 0 tidak termasuk ada pengiriman

**Comment by albeth** [comment]
Di Laporan Pelanggan yang Tidak Ambil ada Opsi : Tidak Ada Pengambilan &/ Tidak Ada Pencetakan Faktur

**Comment by wildanm** [comment]
Done in Changeset: | 1381 (d4e326caf034) 

Jika sudah Ok, close
