### ISSUE TITLE
http://tirtaerp.lodan/reports/customer/tidak/ambil

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#431]
tidak ambil dalam periode terpilih...yg ada muncul semua

**Comment by wildanm** [comment]
Udah bener....

Range periode  itu kan untuk lihat, di range periode itu dia ngambil gak ? 

Ini contohnya, kode konsumen : B20LIN00003 

Di range periode 01-01-2017 s.d 01-31-2017 dia gak ngambil, tapi dibulan selanjutnya dia ada ambil ....

**Comment by wildanm** [comment]
Lihat #432
