### ISSUE TITLE
http://tirtaerp.lodan/reports/customer/tidak/ambil

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#433]
bisa diklik kolom statusnya jd bisa rubah

**Comment by wildanm** [comment]
Maksudnya bisa langsung mengubah status pelanggannya ?

**Comment by albeth** [comment]
Ya

**Comment by wildanm** [comment]
Yang bisa mengubah siapa saja ?

**Comment by albeth** [comment]
Semua bisa

**Comment by wildanm** [comment]
Se, mesti di cek pakai validasi. Kalau setelah periode yg dipilih masih ada pengiriman, tombol ubah statusnya gak bisa..., kalau sebaliknya baru bisa ..., ngerinya, gak teliti yg ngubah. Padahal masih ada pengambilan tapi diubah gak aktif ...

**Comment by albeth** [comment]
Ok

**Comment by wildanm** [comment]
Done in Changeset: | 1382 (5d0026aa6fe9) 

Jika sudah Ok, close
