### ISSUE TITLE
di buat notifikasi di tabel customer di atasnya jika status aktif baru blom masuk rute penagihan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#447]

**Comment by wildanm** [comment]
Jalankan SQL berikut di semua instalasi Tirta ERP : 

`ALTER TABLE tbl_depot ADD is_dilakukan_penagihan INT(1) NULL DEFAULT '1' AFTER is_edit_botolpinjaman;`

**Comment by wildanm** [comment]
`UPDATE tbl_depot SET is_dilakukan_penagihan=1 WHERE ckode_depot IN('U10','O10');`

**Comment by wildanm** [comment]
Done in Changeset: | 1419 (84dc3783cbaf) 

Jika sudah Ok, close
