### ISSUE TITLE
beda print faktur dengan jadwal kirim yg ada di kode pelanggan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#451]
kode pelanggan u10cuc00004 dan u10car00009 
generate faktur 25-11-2017

**Comment by wildanm** [comment]
Done in Changeset: | 1422 (d046da6a7cac) . 

Perbaikan ini, berlaku untuk generate faktur berikutnya. 

Jika sudha Ok, close.
