### ISSUE TITLE
http://erp2012.tirta/reports/daftar/tagihan/per/rute & http://erp2012.tirta/reports/faktur/penagihan/per/rute

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#456]
1. yg rute non aktif tidak muncul
2. kolom rutenya diperbesar sesuai dengan panjang tulisan

**Comment by wildanm** [comment]
Done in Changeset: | 1436 (388166eff91a) 

Jika sudah Ok, close
