### ISSUE TITLE
penyempurnaan pemetaan

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#79]
-Bisa pilih no polisi dengan hari kirim
-hasil pilihannya muncul kolom kode konsumen....nama konsumen.....alamat konsumen database......alamat konsumen pemetaan.....no polisi.....jadwal kirim....jumlah kirim.....tgl terakhir kirim

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

`CREATE TABLE tbl_customer_pemetaan (ckode_customer VARCHAR(11), cnama VARCHAR(100), calamat VARCHAR(100), cnopolisi VARCHAR(10), cpayment CHAR(1) DEFAULT 'K' NOT NULL, rit CHAR(3) DEFAULT 'K' NOT NULL, urut CHAR(3) DEFAULT 'K' NOT NULL, biaya_parkir FLOAT(18, 2), latitude FLOAT(18, 2), longitude FLOAT(18, 2), PRIMARY KEY(ckode_customer)) ENGINE = INNODB;`

**Comment by wildanm** [comment]
Done in 15a2fb1 (bitbucket)
