### ISSUE TITLE
dibuatkan menu untuk hapus konsumen double

### ISSUE THREAD

**Issue by albeth** [OpenThink-Labs/TirtaERP#82]

**Comment by albeth** [comment]
Beda depot

**Comment by wildanm** [comment]
Ini bukannya udah ya, fitur gabung data konsumen ?

**Comment by wildanm** [comment]
Di Master Data Pelanggan --> Klik Lihat Pelanggan -> Gabungkan Data Pelanggan Ini

**Comment by albeth** [comment]
Tapi beda depot gak bisa dan

**Comment by wildanm** [comment]
Bisa, tapi depotnya mesti ada di 1 pc/instalasi tirta erp yang sama, kalau beda pc/instalasi pakai fitur transfer data pelanggan antar depot

**Comment by albeth** [comment]
Ok

**Comment by wildanm** [comment]
Done
